/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_billiard_operator_DistanceComputer */

#ifndef _Included_com_billiard_operator_DistanceComputer
#define _Included_com_billiard_operator_DistanceComputer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_billiard_operator_DistanceComputer
 * Method:    getDistanceFromPoint
 * Signature: (Ljava/lang/String;)D
 */
JNIEXPORT jdouble JNICALL Java_com_billiard_operator_DistanceComputer_getDistanceFromPoint
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
