/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_servlet_Test */

#ifndef _Included_com_servlet_Test
#define _Included_com_servlet_Test
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_servlet_Test
 * Method:    getString
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_servlet_Test_getString
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
